# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file  
      - name: Package
        run: mvn package
      - name: Create JavaDoc
        run: mvn javadoc:javadoc
      - name: javadoc-cleanup
        uses: cicirello/javadoc-cleanup@v1.3.0
        with:
          path-to-root: .
          base-url-path: .
          user-defined-block: .
